apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-web"
  namespace: "default"
  labels:
    app: "my-web"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-web"
  template:
    metadata:
      labels:
        app: "my-web"
    spec:
      containers:
      - name: "myweb-container"
        image: "pralove/myweb:3.0"
